CREATE TABLE users (
  id SERIAL PRIMARY KEY,
	username VARCHAR (55) UNIQUE NOT NULL,
	email VARCHAR (55) UNIQUE NOT NULL,
	first_name VARCHAR (55),
	last_name VARCHAR (55),
	created_at DATE NOT NULL DEFAULT CURRENT_DATE,
	updated_at DATE NOT NULL DEFAULT CURRENT_DATE
);
CREATE TABLE bets (
	id SERIAL PRIMARY KEY,
	title VARCHAR (100),
	description VARCHAR (255),
	odds INTEGER NOT NULL,
	amount_in_cents INTEGER NOT NULL,
	completion_date DATE,
	creator_user_id INTEGER REFERENCES users (id),
	created_at DATE NOT NULL DEFAULT CURRENT_DATE,
	updated_at DATE NOT NULL DEFAULT CURRENT_DATE
);
CREATE TABLE transactions (
	id SERIAL PRIMARY KEY,
	user_id INTEGER REFERENCES users (id),
	bet_id INTEGER REFERENCES bets (id),
	paid BOOLEAN DEFAULT FALSE,
	created_at DATE NOT NULL DEFAULT CURRENT_DATE,
	updated_at DATE NOT NULL DEFAULT CURRENT_DATE
);
